name: Code Coverage

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Install App::Racoco::Report::ReporterCoveralls
        run: zef install --/test 'App::Racoco::Report::ReporterCoveralls:auth<zef:atroxaper>'
      - name: Run RaCoCo
        run: raku -Ilib bin/racoco --reporter=coveralls --exec='prove6 t xt'
        env:
          RAKULIB: './lib'
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
